export const homeObjOne = {
    id: 'about',
    lightBg:true,
    lightText:false,
    lightTextDesc:true,
    topLine:'Broker ',
    headLine:'A person or middleman owrking between the market and the consumer on ',
    description: 'pay him or you die with load of money from companies.',
    buttonLabel:'Know More',
    imgStart:false,
    img:'Icon2',
    alt:'man',
    dark :true,
    primary:true,
    darkText: false,
};

export const homeObjTwo = {
    id: 'services',
    lightBg:false,
    lightText:true,
    lightTextDesc:false,
    topLine:'Discover ',
    headLine:'A person or middleman owrking between the market and the consumer on ',
    description: 'pay him or you die with load of money from companies.',
    buttonLabel:'saver',
    imgStart:true,
    img:require('../../images/svg-5.svg'),
    alt:'goat',
    dark :true,
    primary:true,
    darkText: false,
};

export const homeObjThree = {
    id: 'signup',
    lightBg:true,
    lightText:false,
    lightTextDesc:true,
    topLine:'Broker ',
    headLine:'A person or middleman owrking between the market and the consumer on ',
    description: 'pay him or you die with load of money from companies.',
    buttonLabel:'Find One',
    imgStart:false,
    img:require('../../images/svg-4.svg'),
    alt:'man',
    dark :true,
    primary:true,
    darkText: false,
};

export const homeObjFour= {
    id: 'discover',
    lightBg:false,
    lightText:true,
    lightTextDesc:false,
    topLine:'Broker ',
    headLine:'A person or middleman owrking between the market and the consumer on ',
    description: 'You may die now load of money from companies.',
    buttonLabel:'click here',
    imgStart:true,
    img:require('../../images/svg-2.svg'),
    alt:'dragon',
    dark :true,
    primary:true,
    darkText: false,
};

export const homeObjFive = {
    id: '',
    lightBg:true,
    lightText:false,
    lightTextDesc:true,
    topLine:'Depository Partner ',
    headLine:'A person or middleman owrking between the market and the consumer on ',
    description: 'pay him or you die with load of money from companies.',
    buttonLabel:'Lets Start',
    imgStart:false,
    img:require('../../images/svg-4.svg'),
    alt:'man',
    dark :true,
    primary:true,
    darkText: false,
};